# -*- coding: utf-8 -*-
"""09_06_2023_4potok.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QscJ79Z9SLQvS7Fyp9l9MaMPnD4HXPIa
"""
# Бинарный поиск
def binar(arr, x):
  low = 0
  high = len(arr)-1
  index = -1
  while (low <= high) and (index == -1):
    mid = (low+high) // 2
    if arr[mid] == x:
      index = mid
    else:
      if x < arr[mid]:
        high = mid - 1
      else:
        low = mid + 1
  return index

# Экспоненциальный поиск

def exp_search(arr,x):
  if arr[0] == x:
    return 0
  index = 1
  while index < len(arr) and arr[index] <= x:
    index = index * 2
  return binar(arr[:min(index, len(arr))], x)

testarr = [1,2,3,4,5,7,9,10]
y = int(input("Введи число:"))

if exp_search(testarr,y) != -1:
  print ("Элемен найден под индексом: ", exp_search(testarr,y))
else:
  print ("Элемент не найден в массиве")